#!/bin/sh

OPTS="-i"
# use TTY only if stdin and stdout are both TTYs
if [ -t 0 ] && [ -t 1 ]; then
    OPTS="-it"
fi

if [ "$#" -eq 0 ]; then
    docker exec $OPTS sner_server bash
else
    docker exec $OPTS sner_server "$@"
fi
