"""better user attributes

Revision ID: 1fed81c2e611
Revises: 4885cc76ecfd
Create Date: 2025-04-28 09:33:48.884677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fed81c2e611'
down_revision = '4885cc76ecfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=250), nullable=True))
        batch_op.create_unique_constraint("user_email_key", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint("user_email_key", type_='unique')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
