"""drop vulnsearch

Revision ID: 4885cc76ecfd
Revises: 92b7fe8c937b
Create Date: 2025-03-13 11:15:13.821420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4885cc76ecfd'
down_revision = '92b7fe8c937b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vulnsearch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vulnsearch',
    sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('host_address', postgresql.INET(), autoincrement=False, nullable=False),
    sa.Column('host_hostname', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('service_proto', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('service_port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('via_target', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('cveid', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cvss', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cvss3', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('attack_vector', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('cpe', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('cpe_full', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vulnsearch_pkey')
    )
    # ### end Alembic commands ###
