"""note/vuln add source

Revision ID: 8a837b9c8998
Revises: d2cfafddd156
Create Date: 2026-03-09 10:57:52.669985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a837b9c8998'
down_revision = 'd2cfafddd156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=250), nullable=True))

    with op.batch_alter_table('vuln', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vuln', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
