"""versioninfo add timestamp

Revision ID: d2cfafddd156
Revises: 1fed81c2e611
Create Date: 2025-08-20 19:33:02.795501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2cfafddd156'
down_revision = '1fed81c2e611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versioninfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versioninfo', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
