"""add versioninfo.version_array

Revision ID: fe041e9928e2
Revises: d706f43147e4
Create Date: 2026-04-22 18:40:19.042184

"""

import re

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fe041e9928e2"
down_revision = "d706f43147e4"
branch_labels = None
depends_on = None

VERSION_ARRAY_SIZE = 4

def parse_to_int_array(version_str):
    """compute version_array for existing values"""

    clean = re.sub(r"(?<=[0-9])p(?=[0-9])", ".", version_str)
    clean = clean.split(" ")[0]
    nums = re.findall(r"\d+", clean)

    parts = [int(item) for item in nums[:VERSION_ARRAY_SIZE]]
    if len(parts) < VERSION_ARRAY_SIZE:
        parts.extend([0] * (VERSION_ARRAY_SIZE - len(parts)))

    return parts


def upgrade():
    with op.batch_alter_table("versioninfo", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version_array", postgresql.ARRAY(sa.Integer()), nullable=True))
        batch_op.create_index(batch_op.f("ix_versioninfo_version_array"), ["version_array"], unique=False)

    bind = op.get_bind()
    metadata = sa.MetaData()

    versioninfo_table = sa.Table(
        "versioninfo",
        metadata,
        sa.Column("id", sa.String(32), primary_key=True),
        sa.Column("version", sa.String(250)),
        sa.Column("version_array", postgresql.ARRAY(sa.Integer())),
    )

    query = sa.select(versioninfo_table.c.id, versioninfo_table.c.version)
    results = bind.execute(query).fetchall()
    for row in results:
        v_array = parse_to_int_array(row.version)
        bind.execute(versioninfo_table.update().where(versioninfo_table.c.id == row.id).values(version_array=v_array))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("versioninfo", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_versioninfo_version_array"))
        batch_op.drop_column("version_array")

    # ### end Alembic commands ###
